# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    build_app(workspace: "Gallery.xcworkspace", scheme: "Gallery")
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end
  desc "打包到pgy"
  lane :pgy do |options|
  gym(
   clean:true, #打包前clean项目
   export_method: "ad-hoc", #导出方式
   scheme:"shangshaban", #scheme
   configuration: "Debug",#环境
   output_directory:"./app",#ipa的存放目录
   #output_name:get_build_number()#输出ipa的文件名为当前的build号
  )
  #蒲公英的配置 替换为自己的api_key和user_key
  pgyer(api_key: "f2d70b59d7e14249911cd7b44ea0fa5c", user_key: "14b3a15f9e9299d85836e36e37909e8e",update_description: options[:desc])
  end

end
